#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
fixtures="$root/Fixtures/Verification"
if [ -d "$fixtures" ]; then
  chmod -R u+rwx "$fixtures" 2>/dev/null || true
  rm -rf "$fixtures"
fi
mkdir -p "$fixtures"

mkdir -p "$fixtures/empty-folder"

mkdir -p "$fixtures/small-mixed-folder/Subfolder"
printf 'Meeting notes\n' > "$fixtures/small-mixed-folder/notes.txt"
printf '# FolderPeek fixture\n' > "$fixtures/small-mixed-folder/README.md"
printf '%s' '%PDF-1.4
%EOF
' > "$fixtures/small-mixed-folder/sample.pdf"
printf 'image bytes\n' > "$fixtures/small-mixed-folder/photo.jpg"
printf 'archive bytes\n' > "$fixtures/small-mixed-folder/archive.zip"

mkdir -p "$fixtures/large-mixed-folder"
for i in $(seq -w 1 180); do
  printf 'large fixture item %s\n' "$i" > "$fixtures/large-mixed-folder/item-$i.txt"
done

mkdir -p "$fixtures/visual-folder"
for i in $(seq -w 1 12); do
  printf 'fake image %s\n' "$i" > "$fixtures/visual-folder/image-$i.jpg"
done
printf '%s' '%PDF-1.4
%EOF
' > "$fixtures/visual-folder/reference.pdf"

mkdir -p "$fixtures/archive-containing-folder"
printf 'zip as file only\n' > "$fixtures/archive-containing-folder/materials.zip"
printf 'tar as file only\n' > "$fixtures/archive-containing-folder/export.tar"
printf 'plain note\n' > "$fixtures/archive-containing-folder/readme.txt"

archive_source="$fixtures/.archive-source"
mkdir -p "$archive_source/small/Documents" "$archive_source/small/Images"
printf 'Archive note\n' > "$archive_source/small/Documents/note.txt"
printf '# Archive README\n' > "$archive_source/small/README.md"
printf 'fake image bytes\n' > "$archive_source/small/Images/photo.jpg"
(cd "$archive_source/small" && /usr/bin/zip -qry "$fixtures/small-archive.zip" .)
(cd "$archive_source/small" && LC_ALL=C /usr/bin/bsdtar -cf "$fixtures/small-archive.tar" .)

mkdir -p "$archive_source/nested-unicode/한글 폴더" "$archive_source/nested-unicode/space dir"
printf 'nested unicode\n' > "$archive_source/nested-unicode/한글 폴더/유니코드.txt"
printf 'space path\n' > "$archive_source/nested-unicode/space dir/file with spaces.txt"
(cd "$archive_source/nested-unicode" && /usr/bin/zip -qry "$fixtures/nested-unicode-archive.zip" .)
(cd "$archive_source/nested-unicode" && LC_ALL=C /usr/bin/bsdtar -cf "$fixtures/nested-unicode-archive.tar" .)

mkdir -p "$archive_source/large"
for i in $(seq -w 1 260); do
  printf 'large archive item %s\n' "$i" > "$archive_source/large/archive-item-$i.txt"
done
(cd "$archive_source/large" && /usr/bin/zip -qry "$fixtures/large-archive.zip" .)
(cd "$archive_source/large" && LC_ALL=C /usr/bin/bsdtar -cf "$fixtures/large-archive.tar" .)

printf 'this is not a zip archive\n' > "$fixtures/corrupt-archive.zip"
printf 'this is not a tar archive\n' > "$fixtures/corrupt-archive.tar"
rm -rf "$archive_source"

mkdir -p "$fixtures/dev-looking-folder/src"
printf '# Dev fixture\n' > "$fixtures/dev-looking-folder/README.md"
printf '{"scripts":{"test":"echo no project analysis"}}\n' > "$fixtures/dev-looking-folder/package.json"
printf 'FROM scratch\n' > "$fixtures/dev-looking-folder/Dockerfile"
printf 'print("hello")\n' > "$fixtures/dev-looking-folder/src/main.py"

mkdir -p "$fixtures/thumbnail-failure-folder"
printf 'not really an image\n' > "$fixtures/thumbnail-failure-folder/corrupt.jpg"
printf 'unknown bytes\n' > "$fixtures/thumbnail-failure-folder/file.unknownfolderpeek"

mkdir -p "$fixtures/stale-refresh-folder"
printf 'version 1\n' > "$fixtures/stale-refresh-folder/changing.txt"

mkdir -p "$fixtures/permission-error-folder"
printf 'permission fixture\n' > "$fixtures/permission-error-folder/secret.txt"
chmod 000 "$fixtures/permission-error-folder" 2>/dev/null || true

cat > "$fixtures/README.md" <<'README'
# FolderPeek Verification Fixtures

Generated by `Scripts/create_test_fixtures.sh`.

Fixture coverage:

- `empty-folder/` — empty state.
- `small-mixed-folder/` — normal mixed folder recognition.
- `large-mixed-folder/` — partial/sample disclosure.
- `visual-folder/` — thumbnail candidate cap.
- `archive-containing-folder/` — archives as files, no expansion.
- `small-archive.zip` — selected zip archive file for Quick Look registration and in-process listing.
- `small-archive.tar` — selected tar archive file for Quick Look registration and in-process listing.
- `nested-unicode-archive.zip` / `.tar` — nested, spaces, and Unicode path coverage.
- `large-archive.zip` / `.tar` — listing cap/large archive fixture coverage.
- `corrupt-archive.zip` / `.tar` — deterministic error-state fixtures.
- `dev-looking-folder/` — README/package/Dockerfile/src as ordinary items, no project summary.
- `permission-error-folder/` — access failure where chmod is honored.
- `thumbnail-failure-folder/` — placeholder/failure behavior.
- `stale-refresh-folder/` — update contents between preview invocations for freshness checks.

If `permission-error-folder/` cannot be chmod-protected in the local environment, record it as an explicit test gap.
README

echo "$fixtures"
